version: '3.8' 
                                                                                                                                          
services:
  emotilang-playground:
    build: .
    environment:
      - FLASK_ENV=production
    volumes:
      - ./src:/app/src:ro
      - ./sly:/app/sly:ro
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    user: "1000:1000"  # Run as non-root user
    networks:
      - emotilang-net
    restart: unless-stopped

  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel --url http://emotilang-playground:8080
    networks:
      - emotilang-net

networks:
  emotilang-net:
    driver: bridge
