version: '3.8'

services:
  emotilang-playground:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
    volumes:
      # Mount as read-only for extra security
      - ./src:/app/src:ro
      - ./sly:/app/sly:ro
    # Security settings
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    user: "1000:1000"  # Run as non-root user
    networks:
      - emotilang-net
    restart: unless-stopped

networks:
  emotilang-net:
    driver: bridge
